export const dropdownOptions = {
  AGE_OPTIONS: ['10대 미만', '20-30대', '40-50대', '60대 이상'],
  NATIONALITY_OPTIONS: ['중국', '미국', '터키', '태국', '기타'],
  BUSINESS_INFO_OPTIONS: ['자영업자', '예비창업자', '기타'],
  CATEGORY_OPTIONS: ['Q&A', 'Discussion', 'Help', 'Tips'],
  RESIDENCE_STATUS_OPTIONS: [
    '유학',
    '구직',
    '기업투자',
    '단기종합',
    '일반연수',
    '기타',
  ],
  EXPECTED_STAY_PERIOD_OPTIONS: [
    '3개월 이하',
    '6개월 이하',
    '1년 이하',
    '2년 이하',
    '3년 이하',
    '5년 이하',
    '영주/무기한',
    '모름',
  ],
  WORK_EXPERIENCE_OPTIONS: [
    '없음(0년)',
    '1년 이상',
    '2년 이상',
    '3년 이상',
    '5년 이상',
    '10년 이상',
  ],
  DEGREE_OPTIONS: [
    '없음',
    '고등학교 졸업',
    '전문학사',
    '학사',
    '석사',
    '박사',
    '기타',
  ],
  KOREAN_PROFICIENCY_OPTIONS: [
    '없음',
    '기초 회화 가능(TOPIK 1-2)',
    '중급(TOPIK 3-4)',
    '고급(TOPIK 5-6)',
    '한국 대학교 졸업',
    '기타',
  ],
  INDUSTRY_OPTIONS: [
    '외식업',
    '소매·유통',
    '서비스업',
    'IT',
    '문화·예술',
    '기타',
  ],
};
